## STATISTIQUES

In [6]:
import pandas as pd
import numpy as np

In [7]:
data = pd.read_csv('operations.csv')
data

,date_operation,libelle,montant,solde_avt_ope,categ
0,2023-03-31,DON XX XX XX XX XX XX XX,-1.44,1515.25,AUTRE
1,2023-04-03,CARTE XX XX RAPT XX,-24.00,1513.81,TRANSPORT
2,2023-04-03,CARTE XX XX RAPT XX,-73.00,1489.81,TRANSPORT
3,2023-04-03,VIREMENT XX XX XX XX XX XX XX XX XX XX XX XX,676.00,1416.81,AUTRE
4,2023-04-03,VIREMENT XX XX XX XX XX XX,4.80,2092.81,AUTRE
...,...,...,...,...,...
304,2023-10-05,CARTE XX XX XX XX XX XX,-10.64,2440.94,AUTRE
305,2023-10-05,CARTE XX XX XX XX,-4.80,2430.30,AUTRE
306,2023-10-06,FORFAIT COMPTE SUPERBANK XX XX XX XX,-1.92,2425.50,COTISATION BANCAIRE
307,2023-10-06,CARTE XX XX CHEZ LUC XX,-10.00,2423.58,RESTAURANT
308,2023-10-06,PRELEVEMENT XX TELEPHONE XX XX,-13.58,2413.58,FACTURE TELEPHONE

#### Erreur Type

In [8]:
data.dtypes

date_operation     object
libelle            object
montant           float64
solde_avt_ope     float64
categ              object
dtype: object

In [10]:
data['date_operation'] = pd.to_datetime(data['date_operation'])
data.dtypes

date_operation    datetime64[ns]
libelle                   object
montant                  float64
solde_avt_ope            float64
categ                     object
dtype: object

###### Detectez les erreurs

In [ ]:
data.isnull().sum()

date_operation    0
libelle           0
montant           2
solde_avt_ope     0
categ             1
dtype: int64

In [11]:
#Afficher les valeurs manquantes
nb_nan = data.isnull().sum()
nb_nan[nb_nan>0]

montant    2
categ      1
dtype: int64

In [13]:
# Afficher les valeurs null dans montant
data.loc[data['montant'].isnull(),:]

,date_operation,libelle,montant,solde_avt_ope,categ
107,2023-06-12,CARTE XX XX LES ANCIENS ROBINSON XX,NaN,4667.19,COURSES
269,2023-09-11,CARTE XX XX XX XX,NaN,3401.93,AUTRE

In [ ]:
# 1️⃣ Trier d'abord
data = data.sort_values("date_operation").reset_index(drop=True)

# 2️⃣ Ensuite récupérer les NaN
data_nan = data.loc[data['montant'].isnull(),:]

# 3️⃣ Boucle
for index in data_nan.index:
    data.loc[index, 'montant'] = (
        data.loc[index+1, 'solde_avt_ope']
        - data.loc[index, 'solde_avt_ope']
    )

,date_operation,libelle,montant,solde_avt_ope,categ
0,2023-03-31,DON XX XX XX XX XX XX XX,-1.44,1515.25,AUTRE
1,2023-04-03,CARTE XX XX RAPT XX,-24.00,1513.81,TRANSPORT
2,2023-04-03,CARTE XX XX RAPT XX,-73.00,1489.81,TRANSPORT
3,2023-04-03,VIREMENT XX XX XX XX XX XX XX XX XX XX XX XX,676.00,1416.81,AUTRE
4,2023-04-03,VIREMENT XX XX XX XX XX XX,4.80,2092.81,AUTRE
...,...,...,...,...,...
304,2023-10-05,CARTE XX XX XX XX XX XX,-10.64,2440.94,AUTRE
305,2023-10-05,CARTE XX XX XX XX,-4.80,2430.30,AUTRE
306,2023-10-06,CARTE XX XX CHEZ LUC XX,-10.00,2423.58,RESTAURANT
307,2023-10-06,FORFAIT COMPTE SUPERBANK XX XX XX XX,-1.92,2425.50,COTISATION BANCAIRE
308,2023-10-06,PRELEVEMENT XX TELEPHONE XX XX,-13.58,2413.58,FACTURE TELEPHONE

### Categorie

In [38]:
# regarder les categories manquantes

data.loc[data['categ'].isnull(),:]

,date_operation,libelle,montant,solde_avt_ope,categ
155,2023-07-06,PRELEVEMENT XX TELEPHONE XX XX,-36.48,3295.68,NaN

In [22]:
data.loc[data['libelle'] == 'PRELEVEMENT XX TELEPHONE XX XX', :]

,date_operation,libelle,montant,solde_avt_ope,categ
8,2023-04-05,PRELEVEMENT XX TELEPHONE XX XX,-7.02,2056.02,FACTURE TELEPHONE
65,2023-05-09,PRELEVEMENT XX TELEPHONE XX XX,-7.02,4090.10,FACTURE TELEPHONE
102,2023-06-07,PRELEVEMENT XX TELEPHONE XX XX,-6.38,4688.91,FACTURE TELEPHONE
156,2023-07-06,PRELEVEMENT XX TELEPHONE XX XX,-36.48,3295.68,NaN
204,2023-08-07,PRELEVEMENT XX TELEPHONE XX XX,-7.46,3751.73,FACTURE TELEPHONE
260,2023-09-05,PRELEVEMENT XX TELEPHONE XX XX,-6.38,3453.96,FACTURE TELEPHONE
308,2023-10-06,PRELEVEMENT XX TELEPHONE XX XX,-13.58,2413.58,FACTURE TELEPHONE

In [25]:
data.loc[data['categ'].isnull(),'categ'] == 'FACTURE TELEPHONE'

156    False
Name: categ, dtype: bool

### Doublon

In [32]:
data.loc[data[['date_operation','libelle','montant','solde_avt_ope']].duplicated(keep=False),:]

Empty DataFrame
Columns: [date_operation, libelle, montant, solde_avt_ope, categ]
Index: []

In [31]:
# effacer l'une des doublons 

data.drop_duplicates(subset=['date_operation','libelle','montant','solde_avt_ope'],inplace=True,ignore_index=True)

### Outliers

In [33]:
data.describe()

                      date_operation       montant  solde_avt_ope
count                            308    308.000000     308.000000
mean   2023-07-05 10:59:13.246753280    -45.782013    3395.301071
min              2023-03-31 00:00:00 -15000.000000    1416.810000
25%              2023-05-21 06:00:00    -20.447500    3010.737500
50%              2023-07-05 12:00:00     -9.600000    3452.465000
75%              2023-08-21 00:00:00     -2.715000    3787.232500
max              2023-10-06 00:00:00   1071.600000    4709.310000
std                              NaN    872.818105     667.109412

In [34]:
i = data.loc[data['montant']==-15000,:].index[0] # récupération de l'index de la transaction à -15000

data.iloc[i-1:i+2,:]

,date_operation,libelle,montant,solde_avt_ope,categ
195,2023-08-02,CARTE XX XX RAPT XX,-75.2,3206.75,TRANSPORT
196,2023-08-03,CARTE XX XX XX XX,-15000.0,3797.35,AUTRE
197,2023-08-03,CARTE XX XX CHEZ LUC XX,-10.2,3131.55,RESTAURANT

In [ ]:
data.loc[data['montant']==-15000, 'montant'] = -14.39

,date_operation,libelle,montant,solde_avt_ope,categ
0,2023-03-31,DON XX XX XX XX XX XX XX,-1.44,1515.25,AUTRE
1,2023-04-03,CARTE XX XX RAPT XX,-24.00,1513.81,TRANSPORT
2,2023-04-03,CARTE XX XX RAPT XX,-73.00,1489.81,TRANSPORT
3,2023-04-03,VIREMENT XX XX XX XX XX XX XX XX XX XX XX XX,676.00,1416.81,AUTRE
4,2023-04-03,VIREMENT XX XX XX XX XX XX,4.80,2092.81,AUTRE
...,...,...,...,...,...
303,2023-10-05,CARTE XX XX XX XX XX XX,-10.64,2440.94,AUTRE
304,2023-10-05,CARTE XX XX XX XX,-4.80,2430.30,AUTRE
305,2023-10-06,CARTE XX XX CHEZ LUC XX,-10.00,2423.58,RESTAURANT
306,2023-10-06,FORFAIT COMPTE SUPERBANK XX XX XX XX,-1.92,2425.50,COTISATION BANCAIRE
307,2023-10-06,PRELEVEMENT XX TELEPHONE XX XX,-13.58,2413.58,FACTURE TELEPHONE

,date_operation,libelle,montant,solde_avt_ope,categ
155,2023-07-06,PRELEVEMENT XX TELEPHONE XX XX,-36.48,3295.68,NaN